backend_bucket  = "terraform-state-dev"
backend_key     = "terraform.tfstate"
backend_region  = "us-west-2"
backend_dynamodb_table = "your-terraform-lock-table-dev"
aws_region = "us-east-1" 
access_key_account = "dev_access_key"
secret_key_account = "dev_secret_key"