# Un simple Dockerfile qui exécute un conteneur Nginx
#FROM nginx:latest

FROM nginx:latest

# Copier le fichier nginx.conf personnalisé
COPY nginx.conf /etc/nginx/nginx.conf

# Exposer le port 9090
EXPOSE 9090
