# Un simple Dockerfile qui exécute un conteneur Nginx
#FROM nginx:latest

#FROM nginx:latest

# Exposer le port 8080 au lieu du port par défaut 80
#EXPOSE 9090
# Utiliser l'image officielle d'Apache
FROM httpd:latest
# Exposer le port 8080 (ou un autre port si vous le souhaitez)
EXPOSE 8080
